version: '3.8'
services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: foundobject
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - 3306:3306
    php:
        build: ./docker/php
        volumes:
            - ./:/var/www/html
        depends_on:
            - database
    nginx:
        build: ./docker/nginx
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
    composer:
        image: composer:2
        volumes:
            - ./:/var/www/html

volumes:
    db_data: {}